### ISSUE TITLE
Make it obvious which board slots you can interact with

### ISSUE THREAD

**Issue by martinkadlec0** [hc-tcg/hc-tcg#14]
Right now all slots have the mouse hover effect (shadow + cursor pointer) regardless of player's available moves. We should probably have these only on slots that make sense to click on in given situation.

E.g.:
- Player shouldn't be able to click on opponent's part of the board unless there is a picking process running.
- Player shouldn't be able to click on anything after attacking/changing hermit unless they used some special effect to enable extra action
- Slots that already have cards when a card is selected
- ...

**Comment by hglbrg** [comment]
Would it be possible to write a hook that runs when a card is hovered/selected to highlight its proper slots? 

The same hook could also be used to highlight opponent hermits or own when an effect card is played, I haven't dug hard in the source but there ought to be a state where this is true, yeah?

**Comment by martinkadlec0** [comment]
@hglbrg Should be possible. In redux state on `store.getState().game` there are the `availableActions`, `selectedCard` & `pickProcess` properties. You should be able to use these to get at least he main limitation handled.

**Comment by hglbrg** [comment]
Been ages since I worked with React and Redux but I'll take stab at it.

**Comment by hglbrg** [comment]
I

> Been ages since I worked with React and Redux but I'll take stab at it.

I have not had time to look into to this at all.

**Comment by Tyrannicodin** [comment]
Fiexed by #581
