### ISSUE TITLE
Betrayed may not work properly when the opponent does not pick an AFK Hermit to attack

### ISSUE THREAD

**Issue by alicetouhou** [hc-tcg/hc-tcg#800]
We need someone to investigate, and fix this issue if it is an actual one. The file you need to look at is `common\status-effects\betrayed.ts`, and the `onTimeout` function in the pick request is likely where the issue would be.

**Comment by Lunarmagpie** [comment]
I'm pretty sure this issue may be completely wrong. I think it should be closed.
