### ISSUE TITLE
README should be clear about copying debug config

### ISSUE THREAD

**Issue by Sense101** [hc-tcg/hc-tcg#961]
Right now the README mentions that if you want to make changes to the debug config, you can copy it, and commands are given. However, if you don't copy it you won't actually be able to run the project locally - it will error.

Either it should be stated more clearly that you need to copy the config before the project will run, or ideally a separate check should be in place on running to copy it automatically from the example file, if it's not there.

**Comment by alicetouhou** [comment]
> ideally a separate check should be in place on running to copy it automatically from the example file
Feel free to implement but this seems a bit annoying to make work for every OS. 

I think the best way would be to update the readme. The error you get when you don't copy it is already pretty clear.

**Comment by Sense101** [comment]
Fixed with #963
