### ISSUE TITLE
Confirmation dialogs are not consistent

### ISSUE THREAD

**Issue by Sense101** [hc-tcg/hc-tcg#964]
When confirm dialogs is set to off, sometimes they show and sometimes not.

This needs looking into and fixing.

This is almost certainly an the client code. Dispatching the modal confirm message instead of the modal open message when attempting to open the modal should fix the issue. To make this code easy to verify the correctness, all the logic should be done in the end turn modal. The modal can return `null` if it should not be displayed.

**Comment by alicetouhou** [comment]
Is there a bit at we can remove confirmation dialogues entirely? I think it depends what the goal of them is. There might be a nicer way to achieve it. The current system doesn't feel great, especially with loading modals being a bit slow (at least, it's a lot faster now than it used to be)

**Comment by Lunarmagpie** [comment]
> Is there a bit at we can remove confirmation dialogues entirely? I think it depends what the goal of them is. There might be a nicer way to achieve it. The current system doesn't feel great, especially with loading modals being a bit slow (at least, it's a lot faster now than it used to be)

Modals with show up instantly after #960 so this shouldn't be a big deal.

**Comment by alicetouhou** [comment]
I know they show up instantly, but in my opinion, the system still feels a bit clunky

**Comment by Sense101** [comment]
Started looking into this, the code for modal is scattered across multiple files. I will work on this tomorrow
